#!/bin/sh

# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

# Note: the "Super" modifier is also known as Logo, GUI, Windows, Mod4, etc.

# Remapped to follow my dwl keybindings

# Mod1+Shift+Return to start an instance of foot (https://codeberg.org/dnkl/foot)
riverctl map normal Mod1+Shift Return spawn foot

# Mod1+P to call fuzzel
riverctl map normal Mod1 P spawn fuzzel

# Mod1+Q to close the focused view
riverctl map normal Mod1+Shift C close

# Mod1+Shift+E to exit river
riverctl map normal Mod1+Shift Q spawn wlogout

# Mod1+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal Mod1 J focus-view next
riverctl map normal Mod1 K focus-view previous

# Mod1+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Mod1+Shift J swap next
riverctl map normal Mod1+Shift K swap previous

# Mod1+Period and Super+Comma to focus the next/previous output
riverctl map normal Mod1 Period focus-output next
riverctl map normal Mod1 Comma focus-output previous

# Mod1+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Mod1+Shift Period send-to-output next
riverctl map normal Mod1+Shift Comma send-to-output previous

# Mod1+Return to bump the focused view to the top of the layout stack
riverctl map normal Mod1 Return zoom

# Mod1+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal Mod1 H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Mod1 L send-layout-cmd rivertile "main-ratio +0.05"

# Mod1+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal Mod1+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal Mod1+Shift L send-layout-cmd rivertile "main-count -1"

# Super+Alt+{H,J,K,L} to move views
riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100
riverctl map normal Super+Alt K move up 100
riverctl map normal Super+Alt L move right 100

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right

# Super+Alt+Shift+{H,J,K,L} to resize views
riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift J resize vertical 100
riverctl map normal Super+Alt+Shift K resize vertical -100
riverctl map normal Super+Alt+Shift L resize horizontal 100

# Mod1 + Left Mouse Button to move views
riverctl map-pointer normal Alt BTN_LEFT move-view

# Mod1 + Right Mouse Button to resize views
riverctl map-pointer normal Alt BTN_RIGHT resize-view

# Mod1 + Middle Mouse Button to toggle float
riverctl map-pointer normal Alt BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Mod1+[1-9] to focus tag [0-8]
    riverctl map normal Mod1 $i set-focused-tags $tags

    # Mod1+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Mod1+Shift $i set-view-tags $tags

    # Mod1+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Mod1+Control $i toggle-focused-tags $tags

    # Mod1+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Mod1+Shift+Control $i toggle-view-tags $tags
done

# Mod1+0 to focus all tags
# Mod1+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Mod1 0 set-focused-tags $all_tags
riverctl map normal Mod1+Shift 0 set-view-tags $all_tags

# Mod1+Space to toggle float
riverctl map normal Mod1 Space toggle-float

# Mod1+F to toggle fullscreen
riverctl map normal Mod1 E toggle-fullscreen

# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
riverctl map passthrough Super F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Eject the optical drive (well if you still have one that is)
    riverctl map $mode None XF86Eject spawn 'eject -T'

    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map $mode None XF86AudioRaiseVolume  spawn '/home/tom/.config/dwl/volume.sh up'
    riverctl map $mode None XF86AudioLowerVolume  spawn '/home/tom/.config/dwl/volume.sh down'
    riverctl map $mode None XF86AudioMute         spawn '/hoem/tom/.config/dwl/volume.sh mute'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # Control screen backlight brightness with brightnessctl (https://github.com/Hummer12007/brightnessctl)
    riverctl map $mode None XF86MonBrightnessUp   spawn 'brightnessctl set +5%'
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
    
    #Screenshots
    riverctl map $mode None XF86Print spawn 'grim'
    riverctl map $mode None Shift XF86Print spawn '/home/tom/.config/dwl/grimslurp.sh'
done

# Set background and border color
riverctl background-color 0x002b36
riverctl border-color-focused 0x7fbbb3
riverctl border-color-unfocused 0x83c092

# Make all views with an app-id that starts with "float" and title "foo" start floating.
riverctl rule-add -app-id 'float*' -title 'foo' float

# Make all views with app-id "bar" and any title use client-side decorations
riverctl rule-add -app-id "bar" csd

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 6 -outer-padding 6 &

# Keyboard settings and super shortcuts
riverctl map normal Super Space spawn "/home/tom.config/dwl/imetoggle.sh"
riverctl map normal Super B spawn "qutebrowser"
riverctl map normal Super+Shift B spawn "floorp"
riverctl map normal Super F spawn "pcmanfm-qt"
riverctl map normal Super G spawn "goldendict $(wl-paste -n -p)"
riverctl map normal Super L spawn "waylock -init-color 0x272e33 -input-color 0xa7c080 -fail-color 0xe67e80 -fork-on-lock"
riverctl map normal Super M spawn "/var/lib/flatpak/exports/bin/eu.betterbird.Betterbird"
riverctl map normal Super N spawn "/var/lib/flatpak/exports/bin/com.logseq.Logseq"
riverctl map normal Super O spawn "/var/lib/flatpak/exports/bin/org.libreoffice/LibreOffice"
# Set keyboard repeat rate
riverctl set-repeat 50 300


# Mouse settings
riverctl input pointer-2362-628-PIXA3854:00_093A:0274_Touchpad tap enabled
riverctl input pointer-2362-628-PIXA3854:00_093A:0274_Touchpad tap-button-map left-right-middle
riverctl input pointer-2362-628-PIXA3854:00_093A:0274_Touchpad natural-scroll enabled
riverctl focus-follows-cursor always
riverctl xcursor-theme Future-cursors

# Autostart
riverctl spawn "dbus-update-activation-environment systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river"
riverctl spawn "systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river"
riverctl spawn "wlr-randr --output eDP-1 --scale 1.5"
riverctl spawn "wbg /home/tom/Pictures/gardenofwords1.jpg"
riverctl spawn "waybar -c /home/tom/.config/river/waybar/config.jsonc"
riverctl spawn "/home/tom/.config/dwl/swayidle.sh"
riverctl spawn "dunst"
riverctl spawn "lxqt-policykit-agent"
riverctl spawn "wl-paste --watch cliphist store"
